import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        theme1: {
          navbgcolor: '#000000',
          navbannercolor: '#fff2e7',
          navsociallinks: '#DD90E1',
          navlinkcolor: '#DD90E1',
          musicbgcolor: '#DD90E1',
          musictextcolor: '#000000',
          musicbuttonbgcolor: '#000000',
          musicbuttontextcolor: '#EAC0FF',
          musicbuttonhovertextcolor: '#fa264e',
          tourbgcolor: '#B9DDBA',
          tourbuttonbgcolor: '#FFFFFF',
          tourbuttonbordercolor: '#FFFFFF',
          tourbuttontextcolor: '#DD90E1',
          merchbgcolor:'#fff2e7',
          merchtextcolor: '#fa264e',
          merchbuttonbgcolor: '#eb3d3b',
          merchbuttonhoverbgcolor:'#dd90e1',
          merchbuttontextcolor: '#EAC0FF',
          merchbuttonhovertextcolor:'#ffffff',
          footertextcolor: '#fa264e',
          footersociallinks: '#DD90E1',
          footerBycolor: '#fff2e7',
          tourpagebgcolor: '#b9ddba',
          tourpagetextcolor: '#000000',
          tourpagebuttonbgcolor: '#000000',
          tourpagebuttontextcolor: '#DD90E1',
          tourpagehoverbgcolor: '#fa264e',
          tourpagehoverbutonbgcolor: '#dd90e1',
          tourpagehoverbuttonbordercolor: '#ffffff',
          tourpagehoverbuttontextcolor: '#fa264e',
          tourpagenotificationtext: '#000000',
          followbuttonbgcolor: '#000000',
          followbuttontextcolor: '#DD90E1',
          followbuttonhoverbgcolor: '',
          followbuttonhovertextcolor: '',
          followbuttonhoverbordercolor: '',
          builtbysophiahover:'#DD90E1'
        },
        theme2: {
          navbgcolor: '#161314',
          navbannercolor: '#9DDAED',
          navsociallinks: '#FDF729',
          navlinkcolor: '#FFFFFF',
          musicbgcolor: '#161314',
          musictextcolor: '#E985BA',
          musicbuttonbgcolor: '#606ADC',
          musicbuttontextcolor: '#DD90E1',
          musicbuttonhovertextcolor: '#2FC64d',
          tourbgcolor: '#9DDAED',
          tourbuttonbgcolor: '#EBEA36',
          tourbuttonbordercolor: '#EBEA36',
          tourbuttontextcolor: '#161314',
          merchbgcolor: '#0064E1',
          merchtextcolor: '#f81810',
          merchbuttonbgcolor: '#000000',
          merchbuttonhoverbgcolor: '#161314',
          merchbuttontextcolor: '#ef2018',
          merchbuttonhovertextcolor: '#EBEA36',
          footertextcolor: '#9bdaec',
          footersociallinks: '#FDF729',
          footerBycolor: '#ffffff',
          tourpagebgcolor: '#161314',
          tourpagetextcolor: '#da362f',
          tourpagebuttonbgcolor: '#606ADC',
          tourpagebuttontextcolor: '#2FC64d',
          tourpagehoverbgcolor: '#606ADC',
          tourpagehoverbutonbgcolor: '#000000',
          tourpagehoverbuttonbordercolor: '#000000',
          tourpagehoverbuttontextcolor: '#da362f',
          tourpagenotificationtext: '#2FC64d',
          followbuttonbgcolor: '#606ADC',
          followbuttontextcolor: '#da362f',
          followbuttonhoverbgcolor: '#606ADC',
          followbuttonhovertextcolor: '#2FC64d',
          followbuttonhoverbordercolor: '',
          builtbysophiahover: '#FDF729'
        }
      },
      screens: {
        xxs: "414px",
        xs: "540px",
        md825: "825px",
        md925: "925px",
        lgPlus: "1105px",
        xlPlus: "1220px",
        maxW: "1280px",
        xtraMax: "1360px",
        ultraMax: "1440px",
        ultraMaxPlus: "1520px",
        ultraMaxPlusPlus: "1600px",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
